#!/bin/sh

echo ""
echo "Create by Max (jhaoheng Hu)"
echo "Description:"
echo "Setting vim text color"
echo ""
echo ""

write_color ()
{
	_s1="\n"
	_s2='\n'
	_s3='"——————start vim color——————"\n'
	_s4='syntax on\n'
	_s5='set expandtab\n'
	_s6='set shiftwidth=4\n'
	_s7='set softtabstop=4\n'
	_s8='set tabstop=4\n'
	_s9='set number\n'
	_s10='set cindent\n'
	_s11='set autoindent\n'
    _s12='set hlsearch\n'
	_s13='"——————end vim color-——————"\n'

	str=$_s1$_s2$_s3$_s4$_s5$_s6$_s7$_s8$_s9$_s10$_s11$_s12$_s13

	#echo $str

	echo $str | sudo tee -a  $_path
}

#check vimrc file position
#檢查vimrc的位置
_path=($(sudo find /usr -name vimrc -print))
echo "your 'vimrc' path is : "$_path

#check file "vimrc" is exist
if [ -e $_path ]; then
    echo "File exists"
    echo "..."
    echo "checking syntax..."
    if grep -qF "syntax" $_path
    then
        echo "..."
        echo "syntax is already set,please check the file"
        echo "..."
    else
        echo "..."
        write_color
        echo "setting finish..."
        echo "..."
    fi
else 
    echo "File does not exists"
    echo "..."
fi
echo "done"
echo ""
