#!/bin/sh

echo ""
echo "Create by Max (jhaoheng Hu)"
echo "Description:"
echo "Setting terminal ... color"
echo "..1-directory"
echo "..2-system_link"
echo "..3-socket"
echo "..4-pipe"
echo "..5-executable"
echo "..6-block_special"
echo "..7-char_special"
echo "..8-exe_setuid"
echo "..9-exe_setgid"
echo "..a-dir_writeothers_sticky"
echo "..b-dir_writeothers_NOsticky"
echo ""
echo "you can go to this site to get color str"
echo "--http://geoff.greer.fm/lscolors/--"
echo ""

COLOR_STR='"exfxcxdxbxegedabagacad"';

write_color ()
{
        _s1="\n"
        _s2='\n'
        _s3='"——————start set file/directory color——————"\n'
        _s4="export CLICOLOR='true'\n"
        _s5='export LSCOLORS='$COLOR_STR'\n'
        _s6='"——————end set color-——————"\n'

        str=$_s1$_s2$_s3$_s4$_s5$_s6

        #echo $str

        echo $str >>  $_path
}

#check vimrc file position
#檢查vimrc的位置
_path=($(find ~ -name .bash_profile -print))
echo "your '.bash_profile' path is : "$_path

#check file "vimrc" is exist
if [ -e $_path ]; then
    echo "File exists"
    echo "..."
    echo "checking syntax..."
    if grep -qF "CLICOLOR" $_path
    then
        echo "..."
        echo "syntax is already set,please check the file"
        vim $_path
        echo "..."
    else
        echo "..."
        write_color
        echo "setting finish..."
        echo "..."
    fi  
else 
    echo "File does not exists"
    echo "..."
fi
echo "done"
echo ""
